#!/usr/bin/env sh
rm -f src/Makevars
rm -f src/graphm/graphm
rm -f src/graphm/Makefile
rm -f src/*.o
rm -f src/*.so
rm -f src/graphm/bin/graphm
rm -f src/graphm/*.o
rm -f src/*.rds
rm -f inst/*.o
rm -f inst/*.a
rm -f inst/*.so
rm -f src/graphm/Makefile
