// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// run_graph_match
Rcpp::List run_graph_match(const RcppGSL::Matrix& A, const RcppGSL::Matrix& B, const Rcpp::List& algorithm_params);
RcppExport SEXP RGraphM_run_graph_match(SEXP ASEXP, SEXP BSEXP, SEXP algorithm_paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const RcppGSL::Matrix& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const RcppGSL::Matrix& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type algorithm_params(algorithm_paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(run_graph_match(A, B, algorithm_params));
    return rcpp_result_gen;
END_RCPP
}
